"""baseline_schema

Revision ID: b03b7a457a90
Revises: 
Create Date: 2026-05-28 22:00:34.170304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b03b7a457a90'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cities',
    sa.Column('city_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name_tr', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('plate_code', sa.String(length=2), nullable=False),
    sa.Column('center_lat', sa.Float(), nullable=False),
    sa.Column('center_lng', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('city_id')
    )
    with op.batch_alter_table('cities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cities_city_id'), ['city_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cities_name_tr'), ['name_tr'], unique=False)
        batch_op.create_index(batch_op.f('ix_cities_plate_code'), ['plate_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_cities_slug'), ['slug'], unique=True)

    op.create_table('favorites',
    sa.Column('favorite_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('favorite_id')
    )
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_favorites_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_favorites_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_favorites_favorite_id'), ['favorite_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_favorites_user_id'), ['user_id'], unique=False)

    op.create_table('places',
    sa.Column('place_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('district', sa.String(length=120), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('tags', sa.String(length=255), nullable=False),
    sa.Column('is_partner', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('place_id')
    )
    with op.batch_alter_table('places', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_places_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_places_city'), ['city'], unique=False)
        batch_op.create_index(batch_op.f('ix_places_latitude'), ['latitude'], unique=False)
        batch_op.create_index(batch_op.f('ix_places_longitude'), ['longitude'], unique=False)
        batch_op.create_index(batch_op.f('ix_places_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_places_place_id'), ['place_id'], unique=False)

    op.create_table('route_notes',
    sa.Column('note_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('note_id'),
    sa.UniqueConstraint('user_id', 'route_id', name='uq_user_route_note')
    )
    with op.batch_alter_table('route_notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_route_notes_note_id'), ['note_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_route_notes_route_id'), ['route_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_route_notes_user_id'), ['user_id'], unique=False)

    op.create_table('route_plans',
    sa.Column('plan_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('planned_date', sa.String(length=10), nullable=False),
    sa.Column('planned_time', sa.String(length=5), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('memo', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('plan_id')
    )
    with op.batch_alter_table('route_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_route_plans_plan_id'), ['plan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_route_plans_planned_date'), ['planned_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_route_plans_route_id'), ['route_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_route_plans_user_id'), ['user_id'], unique=False)

    op.create_table('route_reviews',
    sa.Column('review_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('review_id'),
    sa.UniqueConstraint('user_id', 'route_id', name='uq_user_route_review')
    )
    with op.batch_alter_table('route_reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_route_reviews_review_id'), ['review_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_route_reviews_route_id'), ['route_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_route_reviews_user_id'), ['user_id'], unique=False)

    op.create_table('users',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('interests', sa.String(length=500), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('budget', sa.Float(), nullable=False),
    sa.Column('theme_preference', sa.String(length=20), nullable=False),
    sa.Column('preferred_language', sa.String(length=5), nullable=False),
    sa.Column('onboarding_completed', sa.Boolean(), nullable=False),
    sa.Column('xp', sa.Integer(), nullable=False),
    sa.Column('streak_days', sa.Integer(), nullable=False),
    sa.Column('badges', sa.String(length=500), nullable=False),
    sa.Column('last_active_date', sa.String(length=10), nullable=True),
    sa.Column('redeemed_rewards', sa.String(length=1000), nullable=False),
    sa.Column('password_reset_token', sa.String(length=64), nullable=True),
    sa.Column('password_reset_expires', sa.String(length=30), nullable=True),
    sa.Column('is_premium', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_user_id'), ['user_id'], unique=False)

    op.create_table('districts',
    sa.Column('district_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('name_tr', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('center_lat', sa.Float(), nullable=False),
    sa.Column('center_lng', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.city_id'], ),
    sa.PrimaryKeyConstraint('district_id')
    )
    with op.batch_alter_table('districts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_districts_city_id'), ['city_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_districts_district_id'), ['district_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_districts_name_tr'), ['name_tr'], unique=False)
        batch_op.create_index(batch_op.f('ix_districts_slug'), ['slug'], unique=False)

    op.create_table('guide_profiles',
    sa.Column('profile_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('verification_status', sa.String(length=20), nullable=False),
    sa.Column('license_number', sa.String(length=64), nullable=False),
    sa.Column('license_type', sa.String(length=20), nullable=False),
    sa.Column('university', sa.String(length=180), nullable=False),
    sa.Column('department', sa.String(length=180), nullable=False),
    sa.Column('graduation_year', sa.Integer(), nullable=True),
    sa.Column('languages', sa.String(length=200), nullable=False),
    sa.Column('regions', sa.String(length=200), nullable=False),
    sa.Column('document_summary', sa.Text(), nullable=False),
    sa.Column('bio', sa.Text(), nullable=False),
    sa.Column('specialties', sa.String(length=300), nullable=False),
    sa.Column('min_group_size', sa.Integer(), nullable=False),
    sa.Column('max_group_size', sa.Integer(), nullable=False),
    sa.Column('base_price_per_person', sa.Float(), nullable=False),
    sa.Column('rejection_reason', sa.String(length=500), nullable=False),
    sa.Column('document_path', sa.String(length=500), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('profile_id')
    )
    with op.batch_alter_table('guide_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_guide_profiles_user_id'), ['user_id'], unique=True)

    op.create_table('routes',
    sa.Column('route_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('estimated_minutes', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('tags', sa.String(length=255), nullable=False),
    sa.Column('guide_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['guide_id'], ['users.user_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('route_id')
    )
    with op.batch_alter_table('routes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_routes_city'), ['city'], unique=False)
        batch_op.create_index(batch_op.f('ix_routes_guide_id'), ['guide_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_routes_route_id'), ['route_id'], unique=False)

    op.create_table('purchases',
    sa.Column('purchase_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('transaction_ref', sa.String(length=64), nullable=False),
    sa.Column('payment_method', sa.String(length=20), nullable=False),
    sa.Column('offer_id', sa.Integer(), nullable=True),
    sa.Column('trip_request_id', sa.Integer(), nullable=True),
    sa.Column('stripe_session_id', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['route_id'], ['routes.route_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('purchase_id')
    )
    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchases_purchase_id'), ['purchase_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchases_route_id'), ['route_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchases_user_id'), ['user_id'], unique=False)

    op.create_table('quote_requests',
    sa.Column('quote_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tourist_id', sa.Integer(), nullable=False),
    sa.Column('guide_id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=True),
    sa.Column('group_size', sa.Integer(), nullable=False),
    sa.Column('preferred_date', sa.String(length=10), nullable=False),
    sa.Column('preferred_language', sa.String(length=5), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('guide_reply', sa.Text(), nullable=False),
    sa.Column('quoted_total', sa.Float(), nullable=True),
    sa.Column('quoted_per_person', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['guide_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['route_id'], ['routes.route_id'], ),
    sa.ForeignKeyConstraint(['tourist_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('quote_id')
    )
    with op.batch_alter_table('quote_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quote_requests_guide_id'), ['guide_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quote_requests_tourist_id'), ['tourist_id'], unique=False)

    op.create_table('stops',
    sa.Column('stop_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('audio_url', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['route_id'], ['routes.route_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('stop_id')
    )
    with op.batch_alter_table('stops', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stops_route_id'), ['route_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stops_stop_id'), ['stop_id'], unique=False)

    op.create_table('trip_requests',
    sa.Column('request_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tourist_id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('interests', sa.String(length=300), nullable=False),
    sa.Column('group_size', sa.Integer(), nullable=False),
    sa.Column('preferred_date', sa.String(length=10), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('budget', sa.Float(), nullable=False),
    sa.Column('preferred_language', sa.String(length=5), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('route_mode', sa.String(length=20), nullable=False),
    sa.Column('planned_stops', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['route_id'], ['routes.route_id'], ),
    sa.ForeignKeyConstraint(['tourist_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('request_id')
    )
    with op.batch_alter_table('trip_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trip_requests_tourist_id'), ['tourist_id'], unique=False)

    op.create_table('guide_offers',
    sa.Column('offer_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('guide_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('base_total', sa.Float(), nullable=False),
    sa.Column('discount_rate', sa.Float(), nullable=False),
    sa.Column('offered_total', sa.Float(), nullable=False),
    sa.Column('offered_per_person', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['guide_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['trip_requests.request_id'], ),
    sa.PrimaryKeyConstraint('offer_id')
    )
    with op.batch_alter_table('guide_offers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_guide_offers_guide_id'), ['guide_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_guide_offers_request_id'), ['request_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guide_offers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_guide_offers_request_id'))
        batch_op.drop_index(batch_op.f('ix_guide_offers_guide_id'))

    op.drop_table('guide_offers')
    with op.batch_alter_table('trip_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trip_requests_tourist_id'))

    op.drop_table('trip_requests')
    with op.batch_alter_table('stops', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stops_stop_id'))
        batch_op.drop_index(batch_op.f('ix_stops_route_id'))

    op.drop_table('stops')
    with op.batch_alter_table('quote_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quote_requests_tourist_id'))
        batch_op.drop_index(batch_op.f('ix_quote_requests_guide_id'))

    op.drop_table('quote_requests')
    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchases_user_id'))
        batch_op.drop_index(batch_op.f('ix_purchases_route_id'))
        batch_op.drop_index(batch_op.f('ix_purchases_purchase_id'))

    op.drop_table('purchases')
    with op.batch_alter_table('routes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_routes_route_id'))
        batch_op.drop_index(batch_op.f('ix_routes_guide_id'))
        batch_op.drop_index(batch_op.f('ix_routes_city'))

    op.drop_table('routes')
    with op.batch_alter_table('guide_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_guide_profiles_user_id'))

    op.drop_table('guide_profiles')
    with op.batch_alter_table('districts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_districts_slug'))
        batch_op.drop_index(batch_op.f('ix_districts_name_tr'))
        batch_op.drop_index(batch_op.f('ix_districts_district_id'))
        batch_op.drop_index(batch_op.f('ix_districts_city_id'))

    op.drop_table('districts')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_user_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('route_reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_route_reviews_user_id'))
        batch_op.drop_index(batch_op.f('ix_route_reviews_route_id'))
        batch_op.drop_index(batch_op.f('ix_route_reviews_review_id'))

    op.drop_table('route_reviews')
    with op.batch_alter_table('route_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_route_plans_user_id'))
        batch_op.drop_index(batch_op.f('ix_route_plans_route_id'))
        batch_op.drop_index(batch_op.f('ix_route_plans_planned_date'))
        batch_op.drop_index(batch_op.f('ix_route_plans_plan_id'))

    op.drop_table('route_plans')
    with op.batch_alter_table('route_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_route_notes_user_id'))
        batch_op.drop_index(batch_op.f('ix_route_notes_route_id'))
        batch_op.drop_index(batch_op.f('ix_route_notes_note_id'))

    op.drop_table('route_notes')
    with op.batch_alter_table('places', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_places_place_id'))
        batch_op.drop_index(batch_op.f('ix_places_name'))
        batch_op.drop_index(batch_op.f('ix_places_longitude'))
        batch_op.drop_index(batch_op.f('ix_places_latitude'))
        batch_op.drop_index(batch_op.f('ix_places_city'))
        batch_op.drop_index(batch_op.f('ix_places_category'))

    op.drop_table('places')
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_favorites_user_id'))
        batch_op.drop_index(batch_op.f('ix_favorites_favorite_id'))
        batch_op.drop_index(batch_op.f('ix_favorites_entity_type'))
        batch_op.drop_index(batch_op.f('ix_favorites_entity_id'))

    op.drop_table('favorites')
    with op.batch_alter_table('cities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cities_slug'))
        batch_op.drop_index(batch_op.f('ix_cities_plate_code'))
        batch_op.drop_index(batch_op.f('ix_cities_name_tr'))
        batch_op.drop_index(batch_op.f('ix_cities_city_id'))

    op.drop_table('cities')
    # ### end Alembic commands ###
